--JOIN POLICIES POC

--CREATING A JOIN POLICY USING ACCOUNTADMIN ROLE

CREATE JOIN POLICY JOIN_POLICY AS ()
  RETURNS JOIN_CONSTRAINT ->
    CASE
      WHEN CURRENT_ROLE() = 'ACCOUNTADMIN'
        THEN JOIN_CONSTRAINT(JOIN_REQUIRED => FALSE)
      ELSE JOIN_CONSTRAINT(JOIN_REQUIRED => TRUE)
    END;

--CREATING A TBALE WITH ATTCHING JOIN POLICY
    
CREATE OR REPLACE TABLE join_table (
col1 INT,
col2 VARCHAR,
col3 NUMBER )
JOIN POLICY JOIN_POLICY
;

--INSERTING DATA INTO TABLES

INSERT INTO join_table (col1, col2, col3) VALUES (1, 'Sample Data', 123.45);

CREATE OR REPLACE TABLE join_table_details (col1 INT,  col4 VARCHAR,  col5 DATE);

INSERT INTO join_table_details (col1, col4, col5) VALUES (1, 'Additional Info', '2025-03-07');

--PROVIDING GRANTS TO OTHER ROLE

GRANT ALL ON DATABASE PRACTICE TO ROLE SYSADMIN;

GRANT ALL ON SCHEMA R_AND_D_POC TO ROLE SYSADMIN;

GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;

GRANT ALL ON TABLE join_table TO ROLE SYSADMIN;

GRANT ALL ON TABLE join_table_details TO ROLE SYSADMIN;

--QUERYING THE TABLE WITH ACCOUNTADMIN AND SYSADMIN

select * from join_table;
